"""report table unique key added

Revision ID: d0691650b971
Revises: ef32c86483e2
Create Date: 2022-07-28 16:55:38.136444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d0691650b971"
down_revision = "ef32c86483e2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_patient_report", "report", ["patient_id", "report_type"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_patient_report", "report", type_="unique")
    # ### end Alembic commands ###
